package consts

const (
	// TEST_EXCHANGE TEST
	TEST_EXCHANGE = "TEST_EXCHANGE_FANOUT"

	// PC_INDEX_CHANGE PC首页变化消息
	PC_INDEX_CHANGE = "PC_INDEX_CHANGE"

	// MOBILE_INDEX_CHANGE 移动端首页变化消息
	MOBILE_INDEX_CHANGE = "MOBILE_INDEX_CHANGE"

	// GOODS_CHANGE 商品变化消息
	GOODS_CHANGE = "GOODS_CHANGE"

	// GOODS_PRIORITY_CHANGE 商品优先级变化消息
	GOODS_PRIORITY_CHANGE = "GOODS_PRIORITY_CHANGE"

	// GOODS_CHANGE_REASON 商品变化消息附带原因
	GOODS_CHANGE_REASON = "GOODS_CHANGE_REASON"

	//帮助变化消息
	HELP_CHANGE = "HELP_CHANGE"

	//页面生成消息
	PAGE_CREATE = "PAGE_CREATE"

	//索引生成消息
	INDEX_CREATE = "INDEX_CREATE"

	//订单创建消息
	//没有入库
	ORDER_CREATE = "ORDER_CREATE"

	//入库失败消息
	//入库失败
	ORDER_INTODB_ERROR = "ORDER_INTODB_ERROR"

	//订单状态变化消息
	//带入库的
	ORDER_STATUS_CHANGE = "ORDER_STATUS_CHANGE"

	//会员登录消息
	MEMEBER_LOGIN = "MEMEBER_LOGIN"

	//会员注册消息
	MEMEBER_REGISTER = "MEMEBER_REGISTER"

	//店铺变更消息
	SHOP_CHANGE_REGISTER = "SHOP_CHANGE_REGISTER"

	//分类变更消息
	GOODS_CATEGORY_CHANGE = "GOODS_CATEGORY_CHANGE"

	//售后状态改变消息
	REFUND_STATUS_CHANGE = "REFUND_STATUS_CHANGE"

	//发送站内信息
	MEMBER_MESSAGE = "MEMBER_MESSAGE"

	//发送手机短信消息
	SEND_MESSAGE = "SEND_MESSAGE"

	//邮件发送消息
	EMAIL_SEND_MESSAGE = "EMAIL_SEND_MESSAGE"

	//商品评论消息
	GOODS_COMMENT_COMPLETE = "GOODS_COMMENT_COMPLETE"

	//网上支付
	ONLINE_PAY = "ONLINE_PAY"

	//完善个人资料
	MEMBER_INFO_COMPLETE = "MEMBER_INFO_COMPLETE"

	//站点导航栏变化消息
	SITE_NAVIGATION_CHANGE = "SITE_NAVIGATION_CHANGE"

	//商品收藏
	GOODS_COLLECTION_CHANGE = "GOODS_COLLECTION_CHANGE"

	//店铺收藏
	SELLER_COLLECTION_CHANGE = "SELLER_COLLECTION_CHANGE"

	//店铺关闭
	CLOSE_STORE = "CLOSE_STORE"

	//店铺信息发生改变
	SHOP_CHANGE = "SHOP_CHANGE"

	//店铺浏览统计
	SHOP_VIEW_COUNT = "SHOP_VIEW_COUNT"

	//商品浏览统计
	GOODS_VIEW_COUNT = "GOODS_VIEW_COUNT"

	//会员资料改变
	MEMBER_INFO_CHANGE = "MEMBER_INFO_CHANGE"

	//会员历史足迹
	MEMBER_HISTORY = "MEMBER_HISTORY"

	//搜索关键字消息
	SEARCH_KEYWORDS = "SEARCH_KEYWORDS"

	//提示词变更
	GOODS_WORDS_CHANGE = "GOODS_WORDS_CHANGE"

	//拼团成功消息
	PINTUAN_SUCCESS = "PINTUAN_SUCCESS"

	//运费模板变化消息
	SHIP_TEMPLATE_CHANGE = "SHIP_TEMPLATE_CHANGE"

	//会员商品咨询消息
	MEMBER_GOODS_ASK = "MEMBER_GOODS_ASK"

	//会员商品咨询回复消息
	MEMBER_GOODS_ASK_REPLY = "MEMBER_GOODS_ASK_REPLY"

	//商家创建换货或补发商品售后服务新订单消息
	AS_SELLER_CREATE_ORDER = "AS_SELLER_CREATE_ORDER"

	//售后服务单状态改变消息
	AS_STATUS_CHANGE = "AS_STATUS_CHANGE"
)
